version: "3.8"

services:
  vault:
    image: mongo:latest
    container_name: sentry-pod_vault_1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sentry_pod
      MONGO_INITDB_ROOT_PASSWORD: Admin123
    ports:
      - "27017:27017"
    volumes:
      - vault-data:/data/db

  watchman:
    build: ./watchman
    privileged: true
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./watchman:/app${VOLUME_OPTS}
    env_file: ./watchman/.env

  syslog-ng:
    build:
      context: ./watchman
      dockerfile: Dockerfile.syslog-ng
    container_name: sentry-pod_syslog-ng_1
    restart: always
    ports:
      - "10514:10514/udp"
    volumes:
      - ./watchman/playbooks/gns3_lab.conf:/etc/syslog-ng/conf.d/gns3_lab.conf${VOLUME_OPTS}
      - ./watchman/scripts/syslog_listener.sh:/usr/local/bin/syslog_listener.sh${VOLUME_OPTS}
      - ./watchman/playbooks/syslog/:/var/log/syslog/${VOLUME_OPTS}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: localhost/sentry-pod-frontend
    restart: always
    depends_on:
      - watchman
    ports:
      - "3000:80"

volumes:
  vault-data:
