from bson import ObjectId
from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from datetime import datetime

from app.models.playbook import PlaybookRequest, PlaybookResponse
import app.services.playbook_service as playbook_service
from app.database import db
from pydantic import BaseModel
from bson import ObjectId

router = APIRouter(prefix="/playbooks", tags=["Playbooks"])

@router.post("/execute", response_model=PlaybookResponse)
async def execute_playbook(request: PlaybookRequest):
    """Execute an Ansible playbook by name"""
    try:
        returncode, output = playbook_service.run_playbook(request.playbook_name)
        
        # Record audit log entry for this playbook execution
        try:
            audit_col = db.get_collection("audit_logs")
            audit_entry = {
                "action_name": "playbook_execute",
                "playbook_name": request.playbook_name,
                "status": "success" if returncode == 0 else "failed",
                "output": output,
                "username": getattr(request, 'username', 'ChatConsole'),
                "timestamp": datetime.utcnow().isoformat() + "Z",
            }
            await audit_col.insert_one(audit_entry)
        except Exception:
            # Don't fail the playbook response if audit logging fails
            pass
        
        return PlaybookResponse(
            status="success" if returncode == 0 else "failed",
            playbook_name=request.playbook_name,
            message=f"Playbook execution {'completed' if returncode == 0 else 'failed'}",
            output=output
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.get("/execute-stream/{playbook_name}")
async def execute_playbook_stream(playbook_name: str):
    """Execute an Ansible playbook and stream output in real-time using Server-Sent Events"""
    try:
        # Initial validation before entering async stream generator
        playbook_service.validate_playbook_path(playbook_name)
        
        return StreamingResponse(
            playbook_service.run_playbook_stream_generator(playbook_name),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            }
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.get("/list")
async def list_playbooks():
    """List all available playbooks"""
    try:
        playbooks = playbook_service.get_playbook_files()
        return {
            "status": "success",
            "playbooks": playbooks,
            "count": len(playbooks)
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.get("/catalog")
async def get_playbook_catalog():
    """Get the complete playbook catalog with metadata"""
    try:
        catalog = playbook_service.load_catalog()
        return {
            "status": "success",
            "catalog": catalog,
            "count": len(catalog)
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


@router.get("/drift")
async def get_config_drift_reports():
    """Return parsed configuration drift reports generated by playbooks"""
    try:
        reports = playbook_service.parse_config_drift_reports()
        return {"status": "success", "count": len(reports), "reports": reports}
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


@router.get("/drift/{hostname}")
async def get_config_drift_file(hostname: str):
    """Return raw diff report for a specific hostname"""
    try:
        content = playbook_service.read_config_drift_file(hostname)
        return {"status": "success", "hostname": hostname, "content": content}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.post("/drift/refresh")
async def refresh_config_drift():
    """Run drift analysis in container and return updated drift count and reports"""
    import re
    try:
        returncode, output = playbook_service.run_drift_analysis()
        
        # Parse the drift count from output (e.g. "Total Devices with Drift: 16")
        match = re.search(r"Total Devices with Drift:\s*(\d+)", output)
        drift_count = int(match.group(1)) if match else 0
        
        # Fetch updated reports
        reports = playbook_service.parse_config_drift_reports()
        
        # Record audit log entry
        try:
            audit_col = db.get_collection("audit_logs")
            audit_entry = {
                "action_name": "drift_analysis_refresh",
                "status": "success" if returncode == 0 else "failed",
                "output": output,
                "username": "System",
                "drift_count": drift_count,
                "timestamp": datetime.utcnow().isoformat() + "Z",
            }
            await audit_col.insert_one(audit_entry)
        except Exception:
            pass
            
        return {
            "status": "success" if returncode == 0 else "failed",
            "drift_count": drift_count,
            "output": output,
            "reports": reports
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.get("/baseline")
async def get_network_baselines():
    """Return list of baselined devices"""
    try:
        devices = playbook_service.get_baselined_devices()
        return {"status": "success", "count": len(devices), "devices": devices}
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.post("/baseline/refresh")
async def refresh_network_baselines():
    """Run baseline collection in container and return updated baselined devices count"""
    import re
    try:
        returncode, output = playbook_service.run_baseline_collection()
        
        # Parse the baselined devices count from output (e.g. "Total Devices Baselined: 16")
        match = re.search(r"Total Devices Baselined:\s*(\d+)", output)
        baseline_count = int(match.group(1)) if match else 0
        
        # Get list of baselined devices
        devices = playbook_service.get_baselined_devices()
        
        # Record audit log entry
        try:
            audit_col = db.get_collection("audit_logs")
            audit_entry = {
                "action_name": "baseline_collection_refresh",
                "status": "success" if returncode == 0 else "failed",
                "output": output,
                "username": "System",
                "baseline_count": len(devices),
                "timestamp": datetime.utcnow().isoformat() + "Z",
            }
            await audit_col.insert_one(audit_entry)
        except Exception:
            pass
            
        return {
            "status": "success" if returncode == 0 else "failed",
            "baseline_count": len(devices),
            "devices": devices,
            "output": output
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.post("/baseline-graph/refresh")
async def refresh_baseline_graph():
    """Run SNMP collection + parsing in container and return the refreshed host count.

    Drives the Network Baseline graph card on the dashboard.
    """
    import json
    try:
        returncode, output = playbook_service.run_baseline_refresh()

        # Count unique telemetried hosts from per_interface_metrics.json
        host_count = 0
        metrics_path = playbook_service.PLAYBOOKS_DIR / "snmp_output" / "per_interface_metrics.json"
        if metrics_path.exists():
            try:
                data = json.loads(metrics_path.read_text(encoding='utf-8'))
                host_count = len({i.get("host") for i in data.get("interfaces", []) if i.get("host")})
            except Exception:
                host_count = 0

        # Record audit log entry
        try:
            audit_col = db.get_collection("audit_logs")
            audit_entry = {
                "action_name": "baseline_graph_refresh",
                "status": "success" if returncode == 0 else "failed",
                "output": output,
                "username": "System",
                "host_count": host_count,
                "timestamp": datetime.utcnow().isoformat() + "Z",
            }
            await audit_col.insert_one(audit_entry)
        except Exception:
            pass

        return {
            "status": "success" if returncode == 0 else "failed",
            "host_count": host_count,
            "output": output,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


@router.post("/suggest")
async def suggest_playbooks(request: PlaybookRequest):
    """Find playbook suggestions matching a user prompt"""
    try:
        if not request.playbook_name or not request.playbook_name.strip():
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Prompt cannot be empty"
            )
        
        suggestions = playbook_service.find_playbook_suggestions(request.playbook_name, top_k=3)
        return {
            "status": "success",
            "prompt": request.playbook_name,
            "suggestions": suggestions,
            "count": len(suggestions)
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )

@router.get("/inventory/all-hosts-count")
async def get_all_hosts_count():
    """Return the number of devices listed under [allHosts] in hosts.ini."""
    try:
        hostnames = playbook_service.get_all_hosts_from_inventory()
        return {
            "status": "success",
            "group": "allHosts",
            "count": len(hostnames),
            "hosts": hostnames,
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )
    
class AddPlaybookRequest(BaseModel):
    name: str
    engine_type: str
    subnet_scope: str
    pipeline_status: str


@router.post("/add", status_code=status.HTTP_201_CREATED)
async def add_new_playbook(request: AddPlaybookRequest):
    """Save a new registered automation blueprint directly to MongoDB"""
    try:
        playbooks_col = db.get_collection("playbooks")
        
        new_blueprint_doc = {
            "name": request.name,
            "engine_type": request.engine_type,
            "subnet_scope": request.subnet_scope,
            "pipeline_status": request.pipeline_status,
            "last_executed": "Never Executed",
            "timestamp_created": datetime.utcnow().isoformat() + "Z"
        }
        
        await playbooks_col.insert_one(new_blueprint_doc)
        return {"status": "success", "message": f"Successfully committed blueprint: {request.name}"}
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database commit failed: {str(e)}"
        )
    
@router.get("/dashboard")
async def get_playbook_dashboard_data():
    """Return unified playbook metrics and active blueprints directly from MongoDB"""
    try:
        # 1. Connect directly to your live MongoDB playbooks collection
        playbooks_col = db.get_collection("playbooks")
        cursor = playbooks_col.find({})
        
        catalog = []
        async for doc in cursor:
            
            doc["id"] = str(doc["_id"])
            del doc["_id"]
            catalog.append(doc)
        
        total = len(catalog)
        
        #Dynamically calculate your metric cards using your live database documents
        verified = sum(1 for p in catalog if str(p.get("pipeline_status", "")).strip().lower() in ["verified", "production ready"])
        failed = sum(1 for p in catalog if str(p.get("pipeline_status", "")).strip().lower() in ["failed", "error state"])
        draft = sum(1 for p in catalog if str(p.get("pipeline_status", "")).strip().lower() in ["draft", "restricted execution"])

        return {
            "status": "success",
            "total_playbooks": total,
            "verified_pipeline": verified,
            "failed_run_alerts": failed,
            "draft_tasks": draft,
            "blueprints": catalog  
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Dashboard database fetch failed: {str(e)}"
        )
    
    

@router.delete("/delete/{playbook_id}")
async def delete_playbook_entry(playbook_id: str):
    """Permanently delete an automated blueprint record out of MongoDB by its unique hex ID"""
    try:
        playbooks_col = db.get_collection("playbooks")
        

        try:
            mongo_id = ObjectId(playbook_id)
        except Exception:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Provided blueprint asset tracking ID format is completely invalid."
            )
            
        
        result = await playbooks_col.delete_one({"_id": mongo_id})
        
        if result.deleted_count == 0:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Target configuration entry could not be located in database layer."
            )
            
        return {"status": "success", "detail": "Blueprint document successfully dropped from cluster data."}
        
    except HTTPException as he:
        raise he
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Database deletion transaction failure: {str(e)}"
        )