# 1. Define where to listen
source s_gns3_network {
    udp(ip("192.168.122.1") port(10514) so-rcvbuf(1048576));
};

# 2. Define where and how to save the files
destination d_gns3_nodes {
    file("/home/kaveesh/Documents/University/University notes/2nd Year/4th semester/Obsidian/FIS smester 4/Capstone Project/Ansible/Test 1/syslog/$HOST/debug.log" create-dirs(yes)); 
};

# 3. Bind them together
log {
    source(s_gns3_network);
    destination(d_gns3_nodes);
};
