@version: 4.11

source s_gns3_network {
    udp(ip("0.0.0.0") port(10514) so-rcvbuf(1048576) flags(no-parse));
};

destination d_gns3_nodes {
    file("/var/log/syslog/$HOST/debug.log" create-dirs(yes));
};

destination d_listener {
    program("/usr/local/bin/syslog_listener.sh" template("${HOST} ${MESSAGE}\n") no-flow-control timeout(30));
};

log {
    source(s_gns3_network);
    destination(d_gns3_nodes);
    destination(d_listener);
};
