[allHosts]
R1 ansible_host=192.168.122.252
R2 ansible_host=10.0.0.2
ESW1 ansible_host=10.0.0.10
ESW2 ansible_host=10.0.0.20
ESW3 ansible_host=10.0.0.30
ESW4 ansible_host=10.0.0.40
ESW5 ansible_host=10.0.0.50
ESW6 ansible_host=10.0.0.60
ESW7 ansible_host=10.1.99.7
ESW8 ansible_host=10.1.99.8
ESW9 ansible_host=10.1.99.9
ESW10 ansible_host=10.1.99.10
ESW11 ansible_host=10.2.99.11
ESW12 ansible_host=10.2.99.12
ESW13 ansible_host=10.2.99.13
ESW14 ansible_host=10.2.99.14

[Edge_routers]
R1 ansible_host=192.168.122.252
R2 ansible_host=10.0.0.2

[Core_Switches]
ESW1 ansible_host=10.0.0.10
ESW2 ansible_host=10.0.0.20

[Distribution_Switches]
ESW3 ansible_host=10.0.0.30
ESW4 ansible_host=10.0.0.40
ESW5 ansible_host=10.0.0.50
ESW6 ansible_host=10.0.0.60

[HSRP_Routers]
ESW3 ansible_host=10.0.0.30
ESW5 ansible_host=10.0.0.50

[Access_Switches]
ESW7 ansible_host=10.1.99.7 vlan_id=7 vlan_name=Computing defaultGateway=10.1.7.3
ESW8 ansible_host=10.1.99.8 vlan_id=8 vlan_name=Technology defaultGateway=10.1.8.3
ESW9 ansible_host=10.1.99.9 vlan_id=9 vlan_name=Agriculture defaultGateway=10.1.9.3
ESW10 ansible_host=10.1.99.10 vlan_id=10 vlan_name=Geomatics defaultGateway=10.1.10.3
ESW11 ansible_host=10.2.99.11 vlan_id=11 vlan_name=AppliedScience defaultGateway=10.2.11.3
ESW12 ansible_host=10.2.99.12 vlan_id=12 vlan_name=Management defaultGateway=10.2.12.3
ESW13 ansible_host=10.2.99.13 vlan_id=13 vlan_name=Medicine defaultGateway=10.2.13.3
ESW14 ansible_host=10.2.99.14 vlan_id=14 vlan_name=SocialScience defaultGateway=10.2.14.3

[allHosts:vars]
ansible_network_os=cisco.ios.ios
ansible_connection=network_cli
ansible_user=admin
ansible_password=cisco
ansible_become=yes
ansible_become_method=enable

